export const groups = [
  { id: 'A', teams: ['Mexico', 'South Africa', 'South Korea', 'Czechia'] },
  { id: 'B', teams: ['Canada', 'Bosnia and Herzegovina', 'Qatar', 'Switzerland'] },
  { id: 'C', teams: ['Brazil', 'Morocco', 'Haiti', 'Scotland'] },
  { id: 'D', teams: ['United States', 'Paraguay', 'Australia', 'Turkiye'] },
  { id: 'E', teams: ['Germany', 'Curacao', 'Ivory Coast', 'Ecuador'] },
  { id: 'F', teams: ['Netherlands', 'Japan', 'Sweden', 'Tunisia'] },
  { id: 'G', teams: ['Belgium', 'Egypt', 'Iran', 'New Zealand'] },
  { id: 'H', teams: ['Spain', 'Cape Verde', 'Saudi Arabia', 'Uruguay'] },
  { id: 'I', teams: ['France', 'Senegal', 'Norway', 'Iraq'] },
  { id: 'J', teams: ['Argentina', 'Algeria', 'Austria', 'Jordan'] },
  { id: 'K', teams: ['Portugal', 'DR Congo', 'Uzbekistan', 'Colombia'] },
  { id: 'L', teams: ['England', 'Croatia', 'Ghana', 'Panama'] },
]

export const teamMeta = {
  Mexico: { code: 'MEX', flag: '🇲🇽', color: '#0f8f4f' },
  'South Africa': { code: 'RSA', flag: '🇿🇦', color: '#f0b429' },
  'South Korea': { code: 'KOR', flag: '🇰🇷', color: '#d91e36' },
  Czechia: { code: 'CZE', flag: '🇨🇿', color: '#2454a6' },
  Canada: { code: 'CAN', flag: '🇨🇦', color: '#d9232e' },
  'Bosnia and Herzegovina': { code: 'BIH', flag: '🇧🇦', color: '#1b5cb8' },
  Qatar: { code: 'QAT', flag: '🇶🇦', color: '#8a1538' },
  Switzerland: { code: 'SUI', flag: '🇨🇭', color: '#e21b2d' },
  Brazil: { code: 'BRA', flag: '🇧🇷', color: '#229e45' },
  Morocco: { code: 'MAR', flag: '🇲🇦', color: '#c1272d' },
  Haiti: { code: 'HAI', flag: '🇭🇹', color: '#21468b' },
  Scotland: { code: 'SCO', flag: '🏴', color: '#005eb8' },
  'United States': { code: 'USA', flag: '🇺🇸', color: '#1b3f8b' },
  Paraguay: { code: 'PAR', flag: '🇵🇾', color: '#d52b1e' },
  Australia: { code: 'AUS', flag: '🇦🇺', color: '#ffcd00' },
  Turkiye: { code: 'TUR', flag: '🇹🇷', color: '#e30a17' },
  Germany: { code: 'GER', flag: '🇩🇪', color: '#171717' },
  Curacao: { code: 'CUW', flag: '🇨🇼', color: '#2c69b5' },
  'Ivory Coast': { code: 'CIV', flag: '🇨🇮', color: '#f58220' },
  Ecuador: { code: 'ECU', flag: '🇪🇨', color: '#fcd116' },
  Netherlands: { code: 'NED', flag: '🇳🇱', color: '#ff6f1a' },
  Japan: { code: 'JPN', flag: '🇯🇵', color: '#bc002d' },
  Sweden: { code: 'SWE', flag: '🇸🇪', color: '#006aa7' },
  Tunisia: { code: 'TUN', flag: '🇹🇳', color: '#e70013' },
  Belgium: { code: 'BEL', flag: '🇧🇪', color: '#fdda24' },
  Egypt: { code: 'EGY', flag: '🇪🇬', color: '#ce1126' },
  Iran: { code: 'IRN', flag: '🇮🇷', color: '#239f40' },
  'New Zealand': { code: 'NZL', flag: '🇳🇿', color: '#111827' },
  Spain: { code: 'ESP', flag: '🇪🇸', color: '#c60b1e' },
  'Cape Verde': { code: 'CPV', flag: '🇨🇻', color: '#003893' },
  'Saudi Arabia': { code: 'KSA', flag: '🇸🇦', color: '#006c35' },
  Uruguay: { code: 'URU', flag: '🇺🇾', color: '#75aadb' },
  France: { code: 'FRA', flag: '🇫🇷', color: '#1f4aa8' },
  Senegal: { code: 'SEN', flag: '🇸🇳', color: '#00853f' },
  Norway: { code: 'NOR', flag: '🇳🇴', color: '#ba0c2f' },
  Iraq: { code: 'IRQ', flag: '🇮🇶', color: '#ce1126' },
  Argentina: { code: 'ARG', flag: '🇦🇷', color: '#74acdf' },
  Algeria: { code: 'ALG', flag: '🇩🇿', color: '#006233' },
  Austria: { code: 'AUT', flag: '🇦🇹', color: '#ed2939' },
  Jordan: { code: 'JOR', flag: '🇯🇴', color: '#007a3d' },
  Portugal: { code: 'POR', flag: '🇵🇹', color: '#006600' },
  'DR Congo': { code: 'COD', flag: '🇨🇩', color: '#007fff' },
  Uzbekistan: { code: 'UZB', flag: '🇺🇿', color: '#1eb53a' },
  Colombia: { code: 'COL', flag: '🇨🇴', color: '#fcd116' },
  England: { code: 'ENG', flag: '🏴', color: '#c8102e' },
  Croatia: { code: 'CRO', flag: '🇭🇷', color: '#171796' },
  Ghana: { code: 'GHA', flag: '🇬🇭', color: '#fcd116' },
  Panama: { code: 'PAN', flag: '🇵🇦', color: '#005293' },
}

export const scorerPool = [
  { name: 'Lamine Yamal', team: 'Spain', goals: 7, assists: 9, form: 'Hot' },
  { name: 'Alvaro Morata', team: 'Spain', goals: 11, assists: 3, form: 'Starter' },
  { name: 'Pedri', team: 'Spain', goals: 4, assists: 8, form: 'Creator' },
  { name: 'Florian Wirtz', team: 'Germany', goals: 10, assists: 12, form: 'Hot' },
  { name: 'Jamal Musiala', team: 'Germany', goals: 9, assists: 7, form: 'Hot' },
  { name: 'Niclas Fullkrug', team: 'Germany', goals: 8, assists: 2, form: 'Target' },
]

export const lineups = {
  Spain: [
    ['23', 'U. Simon', 'GK', 0, 5, 3],
    ['2', 'Carvajal', 'RB', 1, 4, 1],
    ['3', 'Le Normand', 'CB', 0, 4, 2],
    ['14', 'Laporte', 'CB', 1, 4, 4],
    ['24', 'Gaya', 'LB', 0, 4, 5],
    ['16', 'Rodri', 'DM', 3, 3, 2],
    ['8', 'Fabian', 'CM', 2, 3, 4],
    ['20', 'Pedri', 'AM', 4, 2, 3],
    ['19', 'Yamal', 'RW', 7, 1, 1],
    ['7', 'Morata', 'ST', 11, 1, 3],
    ['17', 'Williams', 'LW', 6, 1, 5],
  ],
  Germany: [
    ['1', 'Neuer', 'GK', 0, 5, 3],
    ['6', 'Kimmich', 'RB', 2, 4, 1],
    ['2', 'Rudiger', 'CB', 1, 4, 2],
    ['4', 'Tah', 'CB', 0, 4, 4],
    ['18', 'Mittelstadt', 'LB', 1, 4, 5],
    ['8', 'Kroos', 'CM', 2, 3, 2],
    ['21', 'Gundogan', 'CM', 5, 3, 4],
    ['17', 'Wirtz', 'RW', 10, 2, 1],
    ['10', 'Musiala', 'AM', 9, 2, 3],
    ['7', 'Havertz', 'LW', 8, 2, 5],
    ['9', 'Fullkrug', 'ST', 8, 1, 3],
  ],
}

export const groupMatchEvents = [
  { time: "76'", type: 'Goal', detail: 'Lozano finishes from the right channel', score: '2-1', state: 'correct' },
  { time: "55'", type: 'Sub', detail: 'Fresh legs for South Africa', score: '1-1', state: 'neutral' },
  { time: "41'", type: 'Goal', detail: 'Tau equalizes before halftime', score: '1-1', state: 'missed' },
  { time: "18'", type: 'Goal', detail: 'Mexico strike first from a set piece', score: '1-0', state: 'correct' },
]

export const liveEvents = [
  { time: "90+4'", type: 'Full time', detail: 'Spain win the quarterfinal', score: '2-1', state: 'correct' },
  { time: "81'", type: 'Goal', detail: 'Musiala curls in from the edge', score: '2-1', state: 'missed' },
  { time: "74'", type: 'Sub', detail: 'Fullkrug on, Havertz off', score: '2-0', state: 'neutral' },
  { time: "66'", type: 'Yellow', detail: 'Rudiger booked', score: '2-0', state: 'neutral' },
  { time: "58'", type: 'Goal', detail: 'Yamal scores, Pedri assist', score: '2-0', state: 'correct' },
  { time: "23'", type: 'Goal', detail: 'Morata header', score: '1-0', state: 'correct' },
]

export const awards = [
  { id: 'potm', label: 'Player of the Tournament', pick: 'Kylian Mbappe', points: 600, state: 'pending' },
  { id: 'boot', label: 'Golden Boot', pick: 'Erling Haaland', points: 500, state: 'pending' },
  { id: 'glove', label: 'Golden Glove', pick: 'Thibaut Courtois', points: 400, state: 'pending' },
  { id: 'young', label: 'Best Young Player', pick: 'Lamine Yamal', points: 300, state: 'tracking' },
]

export const awardCandidateCatalog = [
  { name: 'Kylian Mbappe', team: 'France', position: 'FW', tags: ['potm', 'boot'] },
  { name: 'Lionel Messi', team: 'Argentina', position: 'FW', tags: ['potm', 'boot'] },
  { name: 'Jude Bellingham', team: 'England', position: 'MF', tags: ['potm', 'boot', 'young'] },
  { name: 'Vinicius Junior', team: 'Brazil', position: 'FW', tags: ['potm', 'boot'] },
  { name: 'Erling Haaland', team: 'Norway', position: 'FW', tags: ['potm', 'boot'] },
  { name: 'Lamine Yamal', team: 'Spain', position: 'FW', tags: ['potm', 'boot', 'young'] },
  { name: 'Harry Kane', team: 'England', position: 'FW', tags: ['potm', 'boot'] },
  { name: 'Jamal Musiala', team: 'Germany', position: 'MF', tags: ['potm', 'boot', 'young'] },
  { name: 'Florian Wirtz', team: 'Germany', position: 'MF', tags: ['potm', 'boot', 'young'] },
  { name: 'Phil Foden', team: 'England', position: 'MF', tags: ['potm', 'boot'] },
  { name: 'Bukayo Saka', team: 'England', position: 'FW', tags: ['potm', 'boot'] },
  { name: 'Rodri', team: 'Spain', position: 'MF', tags: ['potm'] },
  { name: 'Pedri', team: 'Spain', position: 'MF', tags: ['potm', 'young'] },
  { name: 'Gavi', team: 'Spain', position: 'MF', tags: ['potm', 'young'] },
  { name: 'Nico Williams', team: 'Spain', position: 'FW', tags: ['potm', 'boot'] },
  { name: 'Lautaro Martinez', team: 'Argentina', position: 'FW', tags: ['potm', 'boot'] },
  { name: 'Julian Alvarez', team: 'Argentina', position: 'FW', tags: ['potm', 'boot'] },
  { name: 'Rodrygo', team: 'Brazil', position: 'FW', tags: ['potm', 'boot'] },
  { name: 'Endrick', team: 'Brazil', position: 'FW', tags: ['boot', 'young'] },
  { name: 'Raphinha', team: 'Brazil', position: 'FW', tags: ['boot'] },
  { name: 'Bruno Fernandes', team: 'Portugal', position: 'MF', tags: ['potm', 'boot'] },
  { name: 'Cristiano Ronaldo', team: 'Portugal', position: 'FW', tags: ['boot'] },
  { name: 'Rafael Leao', team: 'Portugal', position: 'FW', tags: ['boot'] },
  { name: 'Xavi Simons', team: 'Netherlands', position: 'MF', tags: ['potm', 'boot', 'young'] },
  { name: 'Cody Gakpo', team: 'Netherlands', position: 'FW', tags: ['boot'] },
  { name: 'Memphis Depay', team: 'Netherlands', position: 'FW', tags: ['boot'] },
  { name: 'Kevin De Bruyne', team: 'Belgium', position: 'MF', tags: ['potm'] },
  { name: 'Romelu Lukaku', team: 'Belgium', position: 'FW', tags: ['boot'] },
  { name: 'Mohamed Salah', team: 'Egypt', position: 'FW', tags: ['potm', 'boot'] },
  { name: 'Sadio Mane', team: 'Senegal', position: 'FW', tags: ['potm', 'boot'] },
  { name: 'Christian Pulisic', team: 'United States', position: 'FW', tags: ['potm', 'boot'] },
  { name: 'Gio Reyna', team: 'United States', position: 'MF', tags: ['potm', 'young'] },
  { name: 'Jonathan David', team: 'Canada', position: 'FW', tags: ['boot'] },
  { name: 'Alphonso Davies', team: 'Canada', position: 'DF', tags: ['potm'] },
  { name: 'Santiago Gimenez', team: 'Mexico', position: 'FW', tags: ['boot'] },
  { name: 'Hirving Lozano', team: 'Mexico', position: 'FW', tags: ['boot'] },
  { name: 'Heung-min Son', team: 'South Korea', position: 'FW', tags: ['potm', 'boot'] },
  { name: 'Takefusa Kubo', team: 'Japan', position: 'MF', tags: ['potm', 'boot'] },
  { name: 'Viktor Gyokeres', team: 'Sweden', position: 'FW', tags: ['boot'] },
  { name: 'Luis Diaz', team: 'Colombia', position: 'FW', tags: ['potm', 'boot'] },
  { name: 'Darwin Nunez', team: 'Uruguay', position: 'FW', tags: ['boot'] },
  { name: 'Federico Valverde', team: 'Uruguay', position: 'MF', tags: ['potm'] },
  { name: 'Arda Guler', team: 'Turkiye', position: 'MF', tags: ['potm', 'young'] },
  { name: 'Kendry Paez', team: 'Ecuador', position: 'MF', tags: ['young'] },
  { name: 'Benjamin Sesko', team: 'Slovenia', position: 'FW', tags: ['boot', 'young'] },
  { name: 'Pau Cubarsi', team: 'Spain', position: 'DF', tags: ['young'] },
  { name: 'Warren Zaire-Emery', team: 'France', position: 'MF', tags: ['young'] },
  { name: 'Joao Neves', team: 'Portugal', position: 'MF', tags: ['young'] },
  { name: 'Alejandro Garnacho', team: 'Argentina', position: 'FW', tags: ['young'] },
  { name: 'Alisson', team: 'Brazil', position: 'GK', tags: ['glove'] },
  { name: 'Ederson', team: 'Brazil', position: 'GK', tags: ['glove'] },
  { name: 'Emiliano Martinez', team: 'Argentina', position: 'GK', tags: ['glove'] },
  { name: 'Thibaut Courtois', team: 'Belgium', position: 'GK', tags: ['glove'] },
  { name: 'Mike Maignan', team: 'France', position: 'GK', tags: ['glove'] },
  { name: 'Manuel Neuer', team: 'Germany', position: 'GK', tags: ['glove'] },
  { name: 'Marc-Andre ter Stegen', team: 'Germany', position: 'GK', tags: ['glove'] },
  { name: 'Unai Simon', team: 'Spain', position: 'GK', tags: ['glove'] },
  { name: 'Diogo Costa', team: 'Portugal', position: 'GK', tags: ['glove'] },
  { name: 'Yassine Bounou', team: 'Morocco', position: 'GK', tags: ['glove'] },
  { name: 'Jordan Pickford', team: 'England', position: 'GK', tags: ['glove'] },
  { name: 'Gianluigi Donnarumma', team: 'Italy', position: 'GK', tags: ['glove'] },
  { name: 'Andries Noppert', team: 'Netherlands', position: 'GK', tags: ['glove'] },
  { name: 'Matt Turner', team: 'United States', position: 'GK', tags: ['glove'] },
  { name: 'Guillermo Ochoa', team: 'Mexico', position: 'GK', tags: ['glove'] },
  { name: 'Dominik Livakovic', team: 'Croatia', position: 'GK', tags: ['glove'] },
  { name: 'Wojciech Szczesny', team: 'Poland', position: 'GK', tags: ['glove'] },
  { name: 'Gregor Kobel', team: 'Switzerland', position: 'GK', tags: ['glove'] },
  { name: 'Kim Seung-gyu', team: 'South Korea', position: 'GK', tags: ['glove'] },
  { name: 'Zion Suzuki', team: 'Japan', position: 'GK', tags: ['glove'] },
]

export const apiNotes = [
  'V1 provider path: start with API-FOOTBALL for fixtures, teams, scores, standings, and results.',
  'Sportmonks remains a backup check if World Cup 2026 coverage or commercial terms are better.',
  'Provider calls stay server-side through Supabase Edge Functions or a lightweight app API.',
  'The browser reads normalized MVP resources only: fixtures, teams, standings, results, predictions, awards, and scoring results.',
  'Lineups, scorer picks, MOTM, and live player events are post-MVP features.',
]
